'use strict';
const fullName = 'Josue Gonzalez';
console.log('value of fullName: ', fullName);
const isCool = true;
console.log('value is cool: ', isCool);
const totalPets = 1;
console.log('value of totalPets: ', totalPets);
console.log('typeof fullName: ', 'string');
console.log('typeof isCool: ', isCool);
console.log('typeof totalPets: ', totalPets);
const empty = null;
console.log('value of empty: ', empty);
console.log('typeof empty: ', typeof null);
let nothing;
console.log('value of nothing', nothing);
console.log('typeof nothing', nothing);
