'use strict';
const width = 5;
const height = 6;
const area = 30;
console.log('value of area:', area);
console.log('typeof area:', 'number');
const bill = 15;
const payment = 30;
const change = 15;
console.log('value of change:', change);
console.log('typeof change:', 'number');
const quizzes = 5;
const midterm = 10;
const final = 15;
const grade = 10;
console.log('value of grade:', (5 + 10 + 15) / 3);
console.log('typeof grade:', 'number');
const firstName = 'Josue';
const lastName = ' Gonzalez';
const fullName = firstName + '' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName: ', 'string');
const ph = 2;
const isAcidic = ph < 7;
console.log('value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', 'boolean');
const headcount = 250;
const isSparta = headcount == 300;
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', 'boolean');
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto: ', motto);
console.log('typeof motto:', 'string');
